apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: gatus
data:
  config2.yaml: |
    metrics: true
    ui:
      title: "ryzen uptime"
      dashboard-heading: "rynatus"
      default-sort-by: group
  announcements.yaml: |
    announcements: []
  alert.yaml: |
    alerting: {}
  endpoints.yaml: |
    endpoints: []