apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: gatus
data:
  config2.yaml: |
    metrics: true
    ui:
      title: "ryzen uptime"
      dashboard-heading: "rynatus"
      header: "rynatus"
      logo: https://ryzen.me/images/ryzen_calligraphy.png
      buttons:
        - name: Website
          link: https://ryzen.me
      default-sort-by: name
  announcements.yaml: |
    announcements:
      - timestamp: 2026-01-01T00:00:00.000Z
        style: information
        message: https://github.com/ryzenpay/helm-charts/tree/main/gatus
  alerting.yaml: |
    alerting:
      discord:
        webhook-url: $DISCORD_WEBHOOK
        title: ":helmet_with_white_cross: RYNATUS"
        default-alert:
          send-on-resolved: true
  endpoints.yaml: |
    endpoints:
      - name: script.ryzen.me
        url: https://script.ryzen.me/health
        interval: 30s
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
            description: https://script.ryzen.me
      - name: ryzen.me
        url: https://ryzen.me/health
        interval: 30s
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
            description: https://ryzen.me
      - name: harbor container registry
        url: https://harbor.ryzen.me/api/v2.0/health
        interval: 30s
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
            description: https://harbor.ryzen.me
