apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: gatus
data:
  config2.yaml: |
    metrics: true
    ui:
      title: "ryzen uptime"
      dashboard-heading: "rynatus"
      default-sort-by: group
  announcements.yaml: |
    announcements: []
  alert.yaml: |
    alerting: {}
  endpoints.yaml: |
    endpoints:
      - name: scriptinstaller
        url: https://script.ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: website
        url: https://ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: container registry
        url: https://harbor.ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"