apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-conf
  namespace: gatus
data:
  values.yaml: |
    metrics: true
    ui:
      title: "ryzen uptime"
      dashboard-heading: "rynatus"
      default-sort-by: group
    announcements: []
    alerting: {}
    endpoints:
      - name: scriptinstaller
        url: https://script.ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: website
        url: https://ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: container registry
        url: https://harbor.ryzen.me
        interval: 30s
        conditions:
          - "[STATUS] == 200"