annotations: {}
config:
  endpoints: null
deployment:
  annotateConfigChecksum: true
  revisionHistoryLimit: 10
  strategy: RollingUpdate
env:
  GATUS_CONFIG_PATH: /config
envFrom:
  - secretRef:
      name: gatus-secret
extraInitContainers: []
extraLabels: {}
extraVolumeMounts: []
hostNetwork:
  enabled: false
image:
  pullPolicy: IfNotPresent
  repository: twinproduction/gatus
  sha: ''
  tag: ''
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
  enabled: true
  extraPaths: []
  hosts:
    - uptime.ryzen.me
  labels: {}
  path: /
  pathType: Prefix
  tls:
    - hosts:
      - uptime.ryzen.me
      secretName: gatus-tls
labels: {}
livenessProbe:
  enabled: true
networkPolicy:
  enabled: false
  ingress:
    selectors: []
nodeSelector: {}
persistence:
  accessModes:
    - ReadWriteOnce
  enabled: false
  finalizers:
    - kubernetes.io/pvc-protection
  mountPath: /data
  size: 200Mi
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 65534
  sysctls:
    - name: net.ipv4.ping_group_range
      value: 0 65536
priorityClassName: ''
readinessProbe:
  enabled: true
resources: {}
secrets: false
securityContext:
  readOnlyRootFilesystem: true
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
service:
  annotations: {}
  labels: {}
  port: 80
  portName: http
  targetPort: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  autoMount: false
  create: false
  name: ''
serviceMonitor:
  enabled: false
  interval: 1m
  labels: {}
  path: /metrics
  relabelings: []
  scheme: http
  scrapeTimeout: 30s
  tlsConfig: {}
sidecarContainers: {}
tolerations: []
global:
  cattle:
    systemProjectId: p-svwdm
